"""
Chat API routes for RAG-powered Q&A.
Supports streaming responses via SSE.
"""

import json
import logging
from typing import Optional

from fastapi import APIRouter, Query
from pydantic import BaseModel
from sse_starlette.sse import EventSourceResponse

from app.services import rag_service

logger = logging.getLogger("chat_api")

router = APIRouter(prefix="/api/chat", tags=["Chat / RAG"])


class ChatRequest(BaseModel):
    question: str
    document_ids: Optional[list[str]] = None


class ChatResponse(BaseModel):
    answer: str
    sources: list[dict]
    pipeline_info: dict


@router.post("", response_model=ChatResponse)
async def chat(request: ChatRequest):
    """
    Full RAG pipeline: query rewrite → hybrid retrieval → re-rank →
    compress context → generate answer (non-streaming).
    """
    result = rag_service.rag_query(
        question=request.question,
        document_ids=request.document_ids,
        stream=False,
    )
    return ChatResponse(
        answer=result["answer"],
        sources=result.get("sources", []),
        pipeline_info=result.get("pipeline_info", {}),
    )


@router.post("/stream")
async def chat_stream(request: ChatRequest):
    """
    Streaming RAG pipeline: returns SSE events with answer tokens
    as they're generated by Gemini.
    """
    # Run the retrieval pipeline (non-streaming part)
    pipeline_result = rag_service.rag_query(
        question=request.question,
        document_ids=request.document_ids,
        stream=True,
    )

    context = pipeline_result.get("context", "")
    sources = pipeline_result.get("sources", [])
    pipeline_info = pipeline_result.get("pipeline_info", {})

    async def event_generator():
        # Send sources first
        yield {
            "event": "sources",
            "data": json.dumps({"sources": sources, "pipeline_info": pipeline_info}),
        }

        # Stream answer tokens
        for token in rag_service.generate_answer_stream(request.question, context):
            yield {
                "event": "token",
                "data": json.dumps({"token": token}),
            }

        # Send completion signal
        yield {
            "event": "done",
            "data": json.dumps({"status": "complete"}),
        }

    return EventSourceResponse(event_generator())


@router.get("/status")
async def chat_status():
    """Check RAG pipeline status and availability."""
    status = rag_service.get_rag_status()
    return status
